server:
  port: 8000

spring:
  application:
    name: adtech

  data:
    mongodb:
      database: adtech
      port: 27017
      host: localhost

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/adtech?serverTimezone=Asia/Seoul
    username: root
    password: qnwk052911!

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  devtools:
    livereload:
      enabled: true

image:
  advertisement:
    default-path: /Users/admin/IdeaProjects/ad-tech/src/main/resources/static/

pool:
  bid-rate: 0.6
  date-rate: 0.4
